services:
  bronwyn-sweeney:
    image: ghcr.io/alexandermohan/bronwyn-sweeney:latest
    ports:
      - 3000:3000
    volumes:
      - ./persist:/app/persist
      - ./master.key:/app/config/master.key
